// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNNlcRgKRoI9ke8dI60caMnZHtVvPhZ9A',
    appId: '1:231127768627:web:424e7e95cf4d8d59b50d46',
    messagingSenderId: '231127768627',
    projectId: 'flutter-test-28e20',
    authDomain: 'flutter-test-28e20.firebaseapp.com',
    storageBucket: 'flutter-test-28e20.firebasestorage.app',
    measurementId: 'G-6JN59SM3PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvYOaf2Cl11zGVvNyZChK7o5ZVejcC_Pg',
    appId: '1:231127768627:android:cf0e72dff5525c44b50d46',
    messagingSenderId: '231127768627',
    projectId: 'flutter-test-28e20',
    storageBucket: 'flutter-test-28e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-xjG6swi4AHmugk2nrBW3lm8GbNpZM-4',
    appId: '1:231127768627:ios:9d60639eb8ca0354b50d46',
    messagingSenderId: '231127768627',
    projectId: 'flutter-test-28e20',
    storageBucket: 'flutter-test-28e20.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-xjG6swi4AHmugk2nrBW3lm8GbNpZM-4',
    appId: '1:231127768627:ios:9d60639eb8ca0354b50d46',
    messagingSenderId: '231127768627',
    projectId: 'flutter-test-28e20',
    storageBucket: 'flutter-test-28e20.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNNlcRgKRoI9ke8dI60caMnZHtVvPhZ9A',
    appId: '1:231127768627:web:045e1d7a6490da25b50d46',
    messagingSenderId: '231127768627',
    projectId: 'flutter-test-28e20',
    authDomain: 'flutter-test-28e20.firebaseapp.com',
    storageBucket: 'flutter-test-28e20.firebasestorage.app',
    measurementId: 'G-XZDN3G83S2',
  );
}
